// Generated by CoffeeScript 1.3.3

if (Ti.version < 1.8) {
  alert('Sorry - this application template requires Titanium Mobile SDK 1.8 or later');
}

(function() {
  var tab, tabGroup, webView, window;
  window = Ti.UI.createWindow({
    title: L('home'),
    backgroundColor: 'white'
  });
  webView = Ti.UI.createWebView({
    url: 'index.html'
  });
  window.add(webView);
  tab = Ti.UI.createTab({
    title: L('home'),
    icon: '/images/KS_nav_ui.png',
    window: window
  });
  window.containingTab = tab;
  tabGroup = Ti.UI.createTabGroup();
  tabGroup.addTab(tab);
  return tabGroup.open();
})();
